// components/ui/floating-badge.tsx
import { LucideIcon } from "lucide-react";
import { cn } from "@/lib/utils";

interface FloatingBadgeProps {
  icon: LucideIcon;
  label: string;
  className?: string;
}

export function FloatingBadge({ icon: Icon, label, className }: FloatingBadgeProps) {
  return (
    <div
      className={cn(
        "inline-flex items-center gap-1.5 rounded-lg border border-border bg-card px-3 py-1.5 text-xs font-medium text-text-1 shadow-lg backdrop-blur-sm transition-all duration-300 hover:scale-105 hover:border-accent/50 hover:shadow-xl",
        className
      )}
    >
      <Icon size={14} className="text-accent" />
      <span>{label}</span>
    </div>
  );
}

// app/components/sections/hero/FloatingBadge.vue
<script setup lang="ts">
defineProps<{
  icon: Component
  label?: string
}>()
</script>

<template>
  <div
    class="flex items-center gap-2 rounded-xl border border-(--border) bg-(--bg-card)/90 px-3 py-2 text-xs font-semibold text-(--text-1) backdrop-blur-md"
  >
    <span class="flex h-6 w-6 shrink-0 items-center justify-center rounded-md bg-(--accent)/12 text-(--accent)">
      <component :is="icon" :size="12" />
    </span>
    <slot>{{ label }}</slot>
  </div>
</template>
