// components/ui/orbiting-dot.tsx
import { LucideIcon } from "lucide-react";
import { cn } from "@/lib/utils";

interface OrbitingDotProps {
  icon: LucideIcon;
  className?: string;
}

export function OrbitingDot({ icon: Icon, className }: OrbitingDotProps) {
  return (
    <div
      className={cn(
        "flex h-10 w-10 items-center justify-center rounded-full border-2 border-accent/30 bg-card/80 shadow-lg backdrop-blur-sm transition-all duration-300 hover:scale-110 hover:border-accent hover:bg-accent/10",
        className
      )}
    >
      <Icon size={16} className="text-accent" />
    </div>
  );
}

// app/components/sections/hero/OrbitingDot.vue
<script setup lang="ts">
defineProps<{
  icon: Component
}>()
</script>

<template>
  <div class="hidden sm:flex h-8 w-8 items-center justify-center rounded-full border border-(--border) bg-(--bg-card)/90 backdrop-blur-md">
    <component :is="icon" :size="13" class="text-(--accent)" />
  </div>
</template>
